### ISSUE TITLE
Compilation error related to gtest

### ISSUE THREAD

**Issue by scpeters** [osrf/collision-benchmark#5]
I just upgraded my machine to xenial, and now that I'm building this repository again, I'm having cmake errors when trying to find gtest:

~~~
[benchmark_gazebo:cmake] CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
[benchmark_gazebo:cmake]   Could NOT find GTest (missing: GTEST_LIBRARY GTEST_MAIN_LIBRARY)             
[benchmark_gazebo:cmake] Call Stack (most recent call first):                                           
[benchmark_gazebo:cmake]   /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
[benchmark_gazebo:cmake]   /usr/share/cmake-3.5/Modules/FindGTest.cmake:205 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
[benchmark_gazebo:cmake]   CMakeLists.txt:109 (find_package)  
~~~

I have `libgtest-dev` installed, which puts the gtest source code in `/usr/src/gtest` and header files in `/usr/include/gtest`, but it doesn't compile the gtest libraries, since these libraries need to be compiled with the same flags as the rest of the source code. For example, sdformat has a [fork of gtest](https://bitbucket.org/osrf/sdformat/src/bac3dfb42cc72cb609c0bcdbef2064326f5061dd/test/gtest/?at=default) and [compiles it](https://bitbucket.org/osrf/sdformat/src/bac3dfb42cc72cb609c0bcdbef2064326f5061dd/test/CMakeLists.txt?at=default&fileviewer=file-view-default#CMakeLists.txt-22:27) each time you build sdformat.

@JenniferBuehler do you have gtest compiled and installed somewhere?

**Comment by JenniferBuehler** [comment]
Hmmm it's possible I've had it installed locally, though I know it has to be compiled with the same flags... this mistake may have snug in somehow. I'll fix this as soon as I get around to it, hopefully this weekend.

**Comment by JenniferBuehler** [comment]
Sorry for the delay. I've fixed this up, turns out I forgot to set up the cloning properly. Let me know if it works for you now.

**Comment by JenniferBuehler** [comment]
Presuming this has been resolved, closing this. Please re-open if needed.
